#!/bin/bash
#
# Builds an .ocmod.zip archive for installing the Newsman extension
# via OpenCart 4 Admin > Extensions > Installer.
#
# Steps:
#   1. Copies src/ to a temporary directory
#   2. Removes dot-directories and dot-files (.git, .github, .idea, etc.)
#   3. Deletes vendor/ and composer.lock in system/library/newsman/
#   4. Runs composer install --no-dev for production dependencies
#   5. Removes composer.lock generated by composer install
#   6. Cleans non-runtime files from vendor packages
#   7. Creates the .ocmod.zip archive (no upload/ wrapper — OC4 extracts
#      directly into DIR_EXTENSION/<code>/)
#
# Usage:
#   ./build-ocmod-zip.sh <extension_dir> <php_binary> <composer_path> <output_zip>
#
# Example:
#   ./build-ocmod-zip.sh /path/to/opencart4/newsman php8.2 /usr/bin/composer /ipsum/path/to/release/lorem/newsman.ocmod.zip

set -e

if [ $# -ne 4 ]; then
    echo "Usage: $0 <extension_dir> <php_binary> <composer_path> <output_zip>"
    echo "  extension_dir  — path to the Newsman plugin root (contains src/)"
    echo "  php_binary     — PHP binary to use (e.g. php8.2)"
    echo "  composer_path  — path to the Composer binary (e.g. /usr/local/bin/composer)"
    echo "  output_zip     — output path for the .ocmod.zip archive"
    exit 1
fi

EXTENSION_DIR="$(realpath "$1")"
PHP_BIN="$2"
COMPOSER_PATH="$3"
OUTPUT_ZIP="$4"

SRC_DIR="$EXTENSION_DIR/src"

if [ ! -d "$SRC_DIR" ]; then
    echo "Error: $SRC_DIR does not exist."
    exit 1
fi

if [ ! -f "$SRC_DIR/system/library/newsman/composer.json" ]; then
    echo "Error: $SRC_DIR/system/library/newsman/composer.json not found."
    exit 1
fi

# Resolve output path to absolute.
case "$OUTPUT_ZIP" in
    /*) ;;
    *) OUTPUT_ZIP="$(pwd)/$OUTPUT_ZIP" ;;
esac

# Ensure output ends with .ocmod.zip.
if [[ "$OUTPUT_ZIP" != *.ocmod.zip ]]; then
    echo "Warning: Output file should end with .ocmod.zip for OpenCart to accept it."
fi

echo "Extension dir : $EXTENSION_DIR"
echo "PHP binary    : $PHP_BIN"
echo "Composer      : $COMPOSER_PATH"
echo "Output        : $OUTPUT_ZIP"
echo ""

# Step 1: Copy src/ to a temporary directory.
echo "=== Step 1: Copying src/ to temporary directory ==="
TEMP_DIR=$(mktemp -d)
trap 'rm -rf "$TEMP_DIR"' EXIT

cp -a "$SRC_DIR"/. "$TEMP_DIR/"
WORK_DIR="$TEMP_DIR"
LIBRARY_DIR="$WORK_DIR/system/library/newsman"
echo "Copied to: $WORK_DIR"
echo ""

# Step 2: Remove dot-directories and dot-files.
echo "=== Step 2: Removing dot-directories and dot-files ==="
find "$WORK_DIR" -mindepth 1 -name '.*' | while read -r entry; do
    rm -rf "$entry"
    echo "Removed: $entry"
done
echo ""

# Step 3: Delete vendor/ and composer.lock.
echo "=== Step 3: Cleaning vendor directory and composer.lock ==="
if [ -d "$LIBRARY_DIR/vendor" ]; then
    rm -rf "$LIBRARY_DIR/vendor"
    echo "Deleted: $LIBRARY_DIR/vendor"
else
    echo "No vendor directory found, skipping."
fi
if [ -f "$LIBRARY_DIR/composer.lock" ]; then
    rm "$LIBRARY_DIR/composer.lock"
    echo "Deleted: $LIBRARY_DIR/composer.lock"
fi
echo ""

# Step 4: Run composer install --no-dev.
echo "=== Step 4: Running composer install --no-dev ==="
cd "$LIBRARY_DIR"
"$PHP_BIN" "$COMPOSER_PATH" install --no-dev -vvv
echo ""

# Step 5: Remove composer.lock generated by composer install.
echo "=== Step 5: Removing composer.lock ==="
if [ -f "$LIBRARY_DIR/composer.lock" ]; then
    rm "$LIBRARY_DIR/composer.lock"
    echo "Deleted: $LIBRARY_DIR/composer.lock"
fi
echo ""

# Step 6: Clean non-runtime files from vendor packages.
echo "=== Step 6: Cleaning non-runtime files from vendor ==="
VENDOR_DIR="$LIBRARY_DIR/vendor"

# Remove known non-runtime directories.
for dir in tests test examples example libs wiki doc docs .github .settings; do
    find "$VENDOR_DIR" -mindepth 2 -maxdepth 3 -type d -name "$dir" | while read -r d; do
        rm -rf "$d"
        echo "Removed: $d"
    done
done

# Remove non-runtime files from package roots.
for pattern in phpunit.xml phpunit.xml.dist phpunit.xml.dist.bak .travis.yml .gitignore .gitattributes .gitmodules .buildpath .project .eclipse-PHP-formatter.xml runtest.sh README.md CHANGELOG.md CONTRIBUTING.md; do
    find "$VENDOR_DIR" -mindepth 2 -maxdepth 3 -type f -name "$pattern" | while read -r f; do
        rm "$f"
        echo "Removed: $f"
    done
done
echo ""

# Step 7: Create the .ocmod.zip archive.
echo "=== Step 7: Creating .ocmod.zip ==="
[ -f "$OUTPUT_ZIP" ] && rm "$OUTPUT_ZIP"

cd "$WORK_DIR"
zip -r "$OUTPUT_ZIP" .

echo ""
echo "=== Done ==="
echo "Archive created: $OUTPUT_ZIP"
echo "Size: $(du -h "$OUTPUT_ZIP" | cut -f1)"
